name: Android Build CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      HAXELIB_PATH: ${{ github.workspace }}/haxelib

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 5.2.5

      - name: Cache haxelib
        uses: actions/cache@v4
        with:
          path: ${{ env.HAXELIB_PATH }}
          key: ${{ runner.os }}-haxelib

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '11'

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Install dependencies
        run: |
          mkdir -p $HAXELIB_PATH
          haxelib setup $HAXELIB_PATH

          haxelib install lime 7.9.0 --quiet
          haxelib install openfl --quiet
          haxelib install flixel 4.9.0 --quiet
          haxelib install hxcpp --quiet

          haxelib run lime setup
          haxelib run lime setup flixel

          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_ROOT
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

          haxelib install flixel-tools --quiet
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib install hscript --quiet
          haxelib install hxCodec --quiet
          haxelib install newgrounds 1.4.0 --quiet
          haxelib install actuate --quiet

          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/luckydog7/extension-webm
          haxelib git linc_luajit https://github.com/MasterEric/linc_luajit
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit

          haxelib list

      - name: Build APK
        run: haxelib run lime build android -Dci

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Android Build
          path: export/**/android/bin/**/*.apk
